### ISSUE TITLE
Bug when extend edges are unchecked

### ISSUE THREAD

**Issue by CyberMew** [dempseyatgithub/Sample-UISearchController#2]
There seems to be a bug (Apple's?) where the search bar/results will offset by a hard amount if one were to uncheck Extend Edges Under Top Bars. Any idea how to fix that?

Edit: nevermind, I went with Extend Edges Under Top Bars :+1:

**Comment by dempseyatgithub** [comment]
One goal of this project is to keep the sample code as simple and straightforward as possible, so if something does not seem to behave correctly in UISearchController, you can download a zip of the project and use it as a demonstration file for UISearchController bugs.

Please feel free to file a bug at bugreport.apple.com for this issue.
